//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamCMD_reGUI_Client.LOCALE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_by {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_by() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamCMD_reGUI_Client.LOCALE.Strings.by", typeof(Strings_by).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Беларуская.
        /// </summary>
        internal static string sBelarusian {
            get {
                return ResourceManager.GetString("sBelarusian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выканана!.
        /// </summary>
        internal static string sDone {
            get {
                return ResourceManager.GetString("sDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запампоўка завершана!.
        /// </summary>
        internal static string sDownloadingComplete {
            get {
                return ResourceManager.GetString("sDownloadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не павінна быць пустым!.
        /// </summary>
        internal static string sEmptyField {
            get {
                return ResourceManager.GetString("sEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англійская.
        /// </summary>
        internal static string sEnglish {
            get {
                return ResourceManager.GetString("sEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Памылка!.
        /// </summary>
        internal static string sError {
            get {
                return ResourceManager.GetString("sError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гэта першы запуск праграмы. Выканайце наладу!.
        /// </summary>
        internal static string sFirstRun {
            get {
                return ResourceManager.GetString("sFirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прывітанне!.
        /// </summary>
        internal static string sGreeting {
            get {
                return ResourceManager.GetString("sGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... тут.
        /// </summary>
        internal static string sHere {
            get {
                return ResourceManager.GetString("sHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інфармацыя.
        /// </summary>
        internal static string sInformation {
            get {
                return ResourceManager.GetString("sInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова праграммы паспяхова была зменена!.
        /// </summary>
        internal static string sLangChanged {
            get {
                return ResourceManager.GetString("sLangChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка... Калі ласка, пачакайце ....
        /// </summary>
        internal static string sLoading {
            get {
                return ResourceManager.GetString("sLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канфігурацыя паспяхова скінута..
        /// </summary>
        internal static string sReset {
            get {
                return ResourceManager.GetString("sReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руская.
        /// </summary>
        internal static string sRussian {
            get {
                return ResourceManager.GetString("sRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка не существует. Попытаться создать ее?.
        /// </summary>
        internal static string sServersDirectoryNotExistis {
            get {
                return ResourceManager.GetString("sServersDirectoryNotExistis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск.
        /// </summary>
        internal static string sStartP {
            get {
                return ResourceManager.GetString("sStartP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск.
        /// </summary>
        internal static string sStartP1 {
            get {
                return ResourceManager.GetString("sStartP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адмена.
        /// </summary>
        internal static string sStopP {
            get {
                return ResourceManager.GetString("sStopP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адмена.
        /// </summary>
        internal static string sStopP1 {
            get {
                return ResourceManager.GetString("sStopP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распакаванне ....
        /// </summary>
        internal static string sUnpacking {
            get {
                return ResourceManager.GetString("sUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распакаванне ....
        /// </summary>
        internal static string sUnpacking1 {
            get {
                return ResourceManager.GetString("sUnpacking1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распакаванне паспяхова завершана!.
        /// </summary>
        internal static string sUnpackingComplete {
            get {
                return ResourceManager.GetString("sUnpackingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распакаванне паспяхова завершана!.
        /// </summary>
        internal static string sUnpackingComplete1 {
            get {
                return ResourceManager.GetString("sUnpackingComplete1", resourceCulture);
            }
        }
    }
}
