//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamCMD_reGUI_Client.LOCALE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamCMD_reGUI_Client.LOCALE.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config is invalid! Fix it!.
        /// </summary>
        internal static string sCfgInvalid {
            get {
                return ResourceManager.GetString("sCfgInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully saved! Application will restart..
        /// </summary>
        internal static string sCfgSaved {
            get {
                return ResourceManager.GetString("sCfgSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steamcmd.exe not found! Try to download it?.
        /// </summary>
        internal static string sCheckPath {
            get {
                return ResourceManager.GetString("sCheckPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string sDone {
            get {
                return ResourceManager.GetString("sDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete!.
        /// </summary>
        internal static string sDownloadingComplete {
            get {
                return ResourceManager.GetString("sDownloadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field can not be empty!.
        /// </summary>
        internal static string sEmptyField {
            get {
                return ResourceManager.GetString("sEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string sEnglish {
            get {
                return ResourceManager.GetString("sEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string sError {
            get {
                return ResourceManager.GetString("sError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a first run of this program. Please enter default settings!.
        /// </summary>
        internal static string sFirstRun {
            get {
                return ResourceManager.GetString("sFirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        internal static string sGreeting {
            get {
                return ResourceManager.GetString("sGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...here.
        /// </summary>
        internal static string sHere {
            get {
                return ResourceManager.GetString("sHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string sInformation {
            get {
                return ResourceManager.GetString("sInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program language has been changed. .
        /// </summary>
        internal static string sLangChanged {
            get {
                return ResourceManager.GetString("sLangChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.. Please wait.
        /// </summary>
        internal static string sLoading {
            get {
                return ResourceManager.GetString("sLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully reset! Application will restart..
        /// </summary>
        internal static string sReset {
            get {
                return ResourceManager.GetString("sReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string sRussian {
            get {
                return ResourceManager.GetString("sRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string sStartP {
            get {
                return ResourceManager.GetString("sStartP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string sStopP {
            get {
                return ResourceManager.GetString("sStopP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking....
        /// </summary>
        internal static string sUnpacking {
            get {
                return ResourceManager.GetString("sUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking complete.
        /// </summary>
        internal static string sUnpackingComplete {
            get {
                return ResourceManager.GetString("sUnpackingComplete", resourceCulture);
            }
        }
    }
}
